require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe UserEventsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # UserEvent. As you add validations to UserEvent, be sure to
  # adjust the attributes here as well.
     
  let(:valid_attributes) {
    {"name":"test","user_id":"1","start_date":"20161227"}
  }

  let(:invalid_attributes) {
    {"user_event":"ABS","name":"test","user_id":"hello","start_date":""}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UserEventsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #show" do
    it "assigns the requested user_event as @user_event" do
      subject.class.skip_before_action :authenticate_user!
      user_event = UserEvent.create! valid_attributes
      get :show, params: {id: user_event.to_param}, session: valid_session
      expect(assigns(:user_event)).to eq(user_event)
    end
  end

  describe "GET #new" do
    it "assigns a new user_event as @user_event" do
      get :new, params: {}, session: valid_session
      expect(assigns(:user_event)).to be_a_new(UserEvent)
    end
  end

  describe "GET #edit" do
    it "assigns the requested user_event as @user_event" do
      user_event = UserEvent.create! valid_attributes
      get :edit, params: {id: user_event.to_param}, session: valid_session
      expect(assigns(:user_event)).to eq(user_event)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new UserEvent" do
        expect {
          post :create, params: {user_event: valid_attributes}, session: valid_session
        }.to change(UserEvent, :count).by(1)
      end

      it "assigns a newly created user_event as @user_event" do
        post :create, params: {user_event: valid_attributes}, session: valid_session
        expect(assigns(:user_event)).to be_a(UserEvent)
        expect(assigns(:user_event)).to be_persisted
      end

      it "redirects to the created user_event" do
        post :create, params: {user_event: valid_attributes}, session: valid_session
        expect(response).to redirect_to(UserEvent.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved user_event as @user_event" do
        post :create, params: {user_event: invalid_attributes}, session: valid_session
        expect(assigns(:user_event)).to be_a_new(UserEvent)
      end

      it "re-renders the 'new' template" do
        post :create, params: {user_event: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {"name":"test2","user_id":"1","start_date":"20161228"}
      }

      it "updates the requested user_event" do
        user_event = UserEvent.create! valid_attributes
        put :update, params: {id: user_event.to_param, user_event: new_attributes}, session: valid_session
        user_event.reload
        # skip("Add assertions for updated state")
      end

      it "assigns the requested user_event as @user_event" do
        user_event = UserEvent.create! valid_attributes
        put :update, params: {id: user_event.to_param, user_event: valid_attributes}, session: valid_session
        expect(assigns(:user_event)).to eq(user_event)
      end

      it "redirects to the user_event" do
        user_event = UserEvent.create! valid_attributes
        put :update, params: {id: user_event.to_param, user_event: valid_attributes}, session: valid_session
        expect(response).to redirect_to(user_event)
      end
    end

    context "with invalid params" do
      it "assigns the user_event as @user_event" do
        user_event = UserEvent.create! valid_attributes
        put :update, params: {id: user_event.to_param, user_event: invalid_attributes}, session: valid_session
        expect(assigns(:user_event)).to eq(user_event)
      end

      it "re-renders the 'edit' template" do
        user_event = UserEvent.create! valid_attributes
        put :update, params: {id: user_event.to_param, user_event: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested user_event" do
      user_event = UserEvent.create! valid_attributes
      expect {
        delete :destroy, params: {id: user_event.to_param}, session: valid_session
      }.to change(UserEvent, :count).by(-1)
    end

    it "redirects to the user_events list" do
      user_event = UserEvent.create! valid_attributes
      delete :destroy, params: {id: user_event.to_param}, session: valid_session
      expect(response).to redirect_to(user_events_url)
    end
  end

end
